name: Publish to NPM
on:
  push:
    branches: [master]
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
      - name: Yarn Install
        run: yarn
      - name: Run Tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
